# Generated by Django 4.2.4 on 2023-08-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.CharField(max_length=64)),
                ('episode_nb', models.IntegerField(primary_key=True, serialize=False)),
                ('opening_crawl', models.TextField(null=True)),
                ('director', models.CharField(max_length=32, null=True)),
                ('producer', models.CharField(max_length=128, null=True)),
                ('release_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'ex01_movies',
            },
        ),
    ]
